name: Runs All Unit tests

on:
  push:
    branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Step one
              uses: actions/checkout@v2
            - name: Step two
              uses: actions/setup-node@v3
            - name: node install
              run: npm ci
            - run: npm run test
